### PR TITLE
Refactors Relay to use always use Control Pin instead of always using Power Pin.

### LINKED ISSUE #70: Refactor Pump/Relay to use Control Pin instead of Power Pin
As discussed in #32 , Pump and Relay should use Control Pin as their one pin instead of Power pin.

### PR DESCRIPTION
**Pull request by kyleoliveira**
Resolves #70.

@azyth Take a look and let me know if I broke something inadvertently or didn't do enough. See the linked Issue for why I'm doing this.

### CODE REVIEW

**Comment by azyth** [comment]
Just so I am clear, this is the issue we created last semester and just never got around to it?  

What you have done seems fine.  I need to think about it a little though for any other ramifications

**Comment by kyleoliveira** [comment]
Yeah, pretty much. It goes back to #32. If we always have a particular pin set for the equipment, we can then use that pin number as the equipment ID. In part of that discussion, we determined that pretty much everything other than OneWire stuff should always have a Control Pin.

As for ramifications, we'll need to verify on the Ohmbrewer side that it's still sending messages as expected. Since Pump was only using one pin and relying on Relay's one pin constructor, I think this handles any side-effects on the Rhizome side.

**Comment by kyleoliveira** [comment]
@azyth Let me know if this is good to go, it's holding up another, more important, PR.

**Comment by kyleoliveira** [comment]
Seeing no complaints since this has been up for a while, I'm merging it.

**Pull request merged**
