### PR TITLE
adds timers 

### PR DESCRIPTION
**Pull request by azyth**
addresses #42

### CODE REVIEW

**Comment by azyth** [comment]
@kyleoliveira I am having trouble with the timers, i cannot find out a way to init them in the constructors and still have access to them elsewhere. They seem like they where designed primarily for the setup-loop structure.
-I cannot find much documentation specifying how to use them apart from the reference page. 
- I cannot figure out a way to assign a timer to a var so that you can call it from within a class object. 

any ideas?  the timer code is all in place but commented out if you want to see what i would like to be able to do. (initTherm & dowork() & thermostat.h _timer) primarily

**Comment by kyleoliveira** [comment]
So, from what I'm gathering from the Particle docs, the Timer class is a callback model. Think of it kind of like tying a function to an interrupt. Every however many millis, it'll call that function.

As such,
1) There isn't much reason to access the Timer directly. It'll just do it's thang. I think you have the right idea with creating a `doPID` method.

2) Yeah, you're gonna want to create the Timer in the constructor. If we want to manage it (start/stop/rest), then you're probably going to want to set up an instance variable that's a Timer\* and use new to create it in the constructor (kind of like we do with the Temperature variable in TemperatureSensor). It looks like you were trying to do that with `_timer`, but I think the missing component is that it probably needs to be a pointer.

3) Another reason the pointer thing is probably the way to go because it'll allow you to call the dispose() method in the destructor, which will free up one of the 10 available timers if we dynamically remove the equipment. I think we have to do that, but I could be wrong (maybe it disposes itself when the object dies / pointer deletes?).

4) If you don't want to have to constantly start/stop the Timer when the state toggles, you can simply put an if-statement in the function the Timer calls and only do the innards if the state is ON. It would mean the Timer is wasting cycles and could affect the other Timers, but I don't know if that's overly expensive (we'd need to test a bit).

**Comment by kyleoliveira** [comment]
Also, I probably wouldn't try to jam #35 into this. The timer stuff seems challenging enough without mixing that in.

**Comment by azyth** [comment]
Do you think I should make this work in the same way you got the update Timer to work?

**Comment by kyleoliveira** [comment]
Yeah, go for it. I'm still waiting on a useful response to my post on the Particle forum. If we don't figure anything out by the time you're ready to merge, make sure to add an Issue for refactoring it.

**Pull request closed without merging**
